# Note: Make sure to rename this file to "sentinel.yaml" for Sentinel to pick it up

sentinel:
  discordToken: "..."

  # The range of shards to start from shardStart (inclusively) to shardEndExcl (exclusively)
  shardStart: 0
  shardEndExcl: 1

  shardCount: 1 # The total number of shards of your entire bot

spring:
  rabbitmq:
    # These default settings should work without configuring the server
    host: "localhost"
    #host: rabbitmq   # use this when running with the attached docker-compose file
    port: 5672
    username: "guest"
    password: "guest"
